import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "@/components/BootstrapClient";

export const metadata: Metadata = {
  title: "SPEED",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body style={{ background: 'linear-gradient(to right, #f3eeed, #90a5c4)',}}>
        <BootstrapClient />
        {children}
      </body>
    </html>
  );
}
